<?php


namespace Oblood\Foundation;

use Illuminate\Container\Container;
use Oblood\Support\Facade\Request;
use Oblood\Support\Facade\Response;

/**
 * Class Application
 * @package Oblood\Foundation
 *
 * @property Response $response
 * @property Request $request
 */
class Application extends Container
{

    public $server;

    public function __get($key)
    {
        if(isset($this->provider[$key]) && !isset($this[$key])) {
            $this->__set($key , $this->make($this->provider[$key]));
        }
        return parent::__get($key); // TODO: Change the autogenerated stub
    }

    public $provider = [
        'request'   =>  Request::class,
        'response'  =>  Response::class,
    ];
}